name: Translate API CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Используйте нужную вам версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check code formatting with black
      run: |
        pip install black
        black --check .

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run tests with pytest
      run: |
        pip install pytest
        pytest

    - name: Start FastAPI server for integration tests
      run: |
        uvicorn main:app --host 0.0.0.0 --port 8000 &
      env:
        ENVIRONMENT: test

    - name: Run integration tests
      run: |
        pytest integration_tests/
